"use client";
import dynamic from "next/dynamic";
import { useState, useTransition } from "react";
import { readWaypoints, type Waypoint } from "@/lib/trip-planner";
import { saveTripRoute } from "@/lib/trip-planner-actions";
import { inputClass, SaveStatus } from "./PlannerFields";
const RouteMap = dynamic(()=>import("./RouteMapInner"),{ssr:false,loading:()=> <div className="h-80 animate-pulse bg-gray-100" />});
export default function TripRoute({ buildId, value, lat, lng, readOnly = false }: { buildId: string; value: unknown; lat: number | null; lng: number | null; readOnly?: boolean }) {
  const [points,setPoints]=useState(()=>readWaypoints(value)),[editing,setEditing]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false),[pending,start]=useTransition();
  const [name,setName]=useState(""),[latitude,setLatitude]=useState(""),[longitude,setLongitude]=useState(""),[height,setHeight]=useState(""),[kind,setKind]=useState<Waypoint["kind"]>("waypoint");
  function add() {
    const lat=Number(latitude),lng=Number(longitude), elevationM=height===""?null:Number(height);
    if(!name.trim() || !latitude.trim() || !longitude.trim() || !Number.isFinite(lat) || !Number.isFinite(lng) || Math.abs(lat)>90 || Math.abs(lng)>180 || (elevationM!=null && (!Number.isFinite(elevationM) || elevationM < -500 || elevationM>9000))) {setError("Enter a name and valid coordinates. Optional elevation must be between -500 and 9000 m.");return;}
    if(points.length>=200){setError("Maximum 200 waypoints.");return;}
    setPoints([...points,{id:crypto.randomUUID(),name:name.trim(),lat,lng,elevationM,kind}]);setName("");setHeight("");setError("");setSaved(false);
  }
  function move(i:number,delta:number){const next=[...points];[next[i],next[i+delta]]=[next[i+delta],next[i]];setPoints(next);setSaved(false);}
  function submit(f:FormData){setError("");start(async()=>{try{await saveTripRoute(f);setSaved(true);setEditing(false);}catch(e){setError(e instanceof Error?e.message:"Could not save route.");}});}
  const elevations=points.filter(p=>p.elevationM!=null);
  const profileReady=points.length>=2 && elevations.length===points.length;
  const min=Math.min(...elevations.map(p=>p.elevationM!)),max=Math.max(...elevations.map(p=>p.elevationM!));
  return <section id="route" className="scroll-mt-20 overflow-hidden rounded-3xl border border-gray-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 p-5 sm:px-8"><div><h2 className="text-xl font-bold">Route</h2><p className="mt-1 text-sm text-gray-500">Trailheads, camps, water stops, and waypoints in travel order.</p></div>{!readOnly && <button type="button" disabled={pending} onClick={()=>{if(editing){setPoints(readWaypoints(value));setError("");}setEditing(!editing);setSaved(false);}} className="rounded-xl border px-4 py-2 text-sm font-semibold">{editing?"Cancel editing":"Edit route"}</button>}</div>
    <RouteMap points={points} fallback={lat!=null&&lng!=null?[lat,lng]:null} onPick={editing&&!pending ? (a,b)=>{setLatitude(a.toFixed(6));setLongitude(b.toFixed(6));}:undefined} />
    <div className="space-y-4 p-5 sm:px-8"><p className="text-xs text-gray-500">Dashed lines connect waypoints directly; they do not follow trails. Enter daily walking distances in the itinerary.</p>
      {profileReady ? <div><p className="text-xs font-semibold text-gray-600">Waypoint elevations · {min}–{max} m · evenly spaced stops</p><svg viewBox="0 0 600 100" role="img" aria-label="Elevation at each waypoint, ordered by travel, not distance" className="mt-2 h-24 w-full"><polyline fill="none" stroke="#166534" strokeWidth="3" points={points.map((p,i)=>`${10+i*580/(points.length-1)},${85-((p.elevationM!-min)/Math.max(1,max-min))*70}`).join(" ")} /></svg></div> : <p className="text-xs text-gray-400">Add elevation to every waypoint (at least two) to see an elevation sketch.</p>}
      {!points.length && <p className="text-sm text-gray-500">No route waypoints yet.</p>}
      <ol className="space-y-2">{points.map((p,i)=><li key={p.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-gray-50 px-3 py-2 text-sm"><div><strong>{i+1}. {p.name}</strong><span className="ml-2 text-gray-500">{p.kind} · {p.lat.toFixed(4)}, {p.lng.toFixed(4)}{p.elevationM!=null?` · ${p.elevationM} m`:""}</span></div>{editing && <div className="flex gap-3"><button type="button" disabled={pending||i===0} aria-label={`Move ${p.name} earlier`} onClick={()=>move(i,-1)} className="disabled:opacity-30">↑</button><button type="button" disabled={pending||i===points.length-1} aria-label={`Move ${p.name} later`} onClick={()=>move(i,1)} className="disabled:opacity-30">↓</button><button type="button" disabled={pending} onClick={()=>{setPoints(points.filter(x=>x.id!==p.id));setSaved(false);}} className="text-red-700">Remove</button></div>}</li>)}</ol>
      {editing && <form action={submit} className="space-y-4 border-t pt-4"><input type="hidden" name="buildId" value={buildId} /><input type="hidden" name="waypoints" value={JSON.stringify(points)} /><fieldset disabled={pending} className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Stop name<input value={name} maxLength={200} onChange={e=>setName(e.target.value)} className={inputClass} /></label><label className="text-sm">Type<select value={kind} onChange={e=>setKind(e.target.value as Waypoint["kind"])} className={inputClass}>{["trailhead","camp","water","waypoint"].map(k=><option key={k}>{k}</option>)}</select></label><label className="text-sm">Latitude<input value={latitude} onChange={e=>setLatitude(e.target.value)} className={inputClass} /></label><label className="text-sm">Longitude<input value={longitude} onChange={e=>setLongitude(e.target.value)} className={inputClass} /></label><label className="text-sm">Elevation (m, optional)<input value={height} onChange={e=>setHeight(e.target.value)} className={inputClass} /></label><button type="button" onClick={add} className="self-end rounded-xl border border-green-700 px-4 py-2.5 text-sm font-semibold text-green-800">Add waypoint</button></fieldset><p className="text-xs text-gray-500">Click the map to fill coordinates. Add the stop, then save your route.</p><SaveStatus pending={pending} error={error} saved={saved} /></form>}
      {!editing&&saved&&<p aria-live="polite" className="text-sm text-green-700">Route saved.</p>}
    </div></section>;
}
